# Generated by Django 5.0.2 on 2025-11-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0004_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materias',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_escolar_desit_api.maestros'),
        ),
        migrations.AddField(
            model_name='materias',
            name='programa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materias',
            name='salon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materias',
            name='seccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
